2020-10-21 10:02:35,602 - Shuake.py[line:409] - INFO: 运行
2020-10-21 10:02:49,892 - Shuake.py[line:409] - INFO: 运行
2020-10-21 17:10:56,519 - Shuake.py[line:412] - INFO: 运行
2020-10-21 17:13:20,037 - Shuake.py[line:154] - ERROR: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 142, in init_PageList
    self.pageList[int(page['courseId'])].append(_page)
KeyError: 215091538
2020-10-21 17:13:20,039 - Shuake.py[line:155] - INFO: 18845142702	获取视频列表失败
2020-10-21 17:13:42,584 - Shuake.py[line:412] - INFO: 运行
2020-10-21 17:13:43,453 - Shuake.py[line:154] - ERROR: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 144, in init_PageList
    self.pageList[int(page['courseId'])].append(_page)
KeyError: 215091538
2020-10-21 17:13:43,456 - Shuake.py[line:155] - INFO: 18845142702	获取视频列表失败
2020-10-21 17:14:08,610 - Shuake.py[line:413] - INFO: 运行
2020-10-21 17:14:09,424 - Shuake.py[line:155] - ERROR: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 144, in init_PageList
    self.pageList[int(page['courseId'])].append(_page)
KeyError: 215091538
2020-10-21 17:14:09,426 - Shuake.py[line:156] - INFO: 18845142702	获取视频列表失败
2020-10-21 17:17:01,016 - Shuake.py[line:421] - INFO: 运行
2020-10-21 17:18:51,867 - Shuake.py[line:421] - INFO: 运行
2020-10-21 17:26:48,521 - Shuake.py[line:421] - INFO: 运行
2020-10-21 17:27:53,696 - Shuake.py[line:421] - INFO: 运行
2020-10-21 17:36:41,961 - Shuake.py[line:427] - INFO: 运行
2020-10-21 17:43:43,749 - Shuake.py[line:426] - INFO: 运行
2020-10-21 17:43:44,328 - Shuake.py[line:166] - ERROR: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 128, in init_PageList
    if self.jnodeList[jnodeid]['coursename'] == "四史学习":
TypeError: list indices must be integers or slices, not dict
2020-10-21 17:43:44,329 - Shuake.py[line:167] - INFO: 18845142702	获取视频列表失败
2020-10-21 17:43:49,806 - Shuake.py[line:426] - INFO: 运行
2020-10-21 17:49:44,778 - Shuake.py[line:431] - INFO: 运行
2020-10-21 17:49:45,450 - Shuake.py[line:98] - ERROR: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 95, in init_jnodeList
    self.jnodeList[courseId].sort(key=jnode_sort)
TypeError: jnode_sort() missing 1 required positional argument: 'jnode2'
2020-10-21 17:49:45,452 - Shuake.py[line:99] - INFO: 18845142702	获取课程列表失败
2020-10-21 17:49:45,453 - Shuake.py[line:171] - ERROR: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 133, in init_PageList
    if self.jnodeList[jnodeid]['coursename'] == "四史学习":
TypeError: list indices must be integers or slices, not str
2020-10-21 17:49:45,454 - Shuake.py[line:172] - INFO: 18845142702	获取视频列表失败
2020-10-21 17:51:38,228 - Shuake.py[line:431] - INFO: 运行
2020-10-21 17:52:58,864 - Shuake.py[line:431] - INFO: 运行
2020-10-21 18:57:11,825 - Shuake.py[line:431] - INFO: 运行
2020-10-21 19:06:34,269 - Shuake.py[line:431] - INFO: 运行
2020-10-21 19:06:34,570 - Shuake.py[line:58] - ERROR: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 55, in login
    self.puid = re.search(r"puid\":(.*?),", resp).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2020-10-21 19:06:34,572 - Shuake.py[line:59] - INFO: 18845142702登陆失败
2020-10-21 19:06:34,572 - Shuake.py[line:418] - INFO: 王文安	： 密码错误
2020-10-21 19:06:45,446 - Shuake.py[line:431] - INFO: 运行
2020-10-21 21:24:00,905 - Shuake.py[line:374] - INFO: 运行
2020-10-21 21:27:38,760 - Shuake.py[line:374] - INFO: 运行
2020-10-21 21:27:39,350 - Shuake.py[line:199] - ERROR: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 178, in shuake
    cardsInfoList, reportInfo, success = self.get_cards_info(knowledge, num)
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 124, in get_cards_info
    clazzid = knowledge['clazzId']
KeyError: 'clazzId'
2020-10-21 21:27:39,351 - Shuake.py[line:200] - INFO: 18845142702	刷课意外
2020-10-21 21:28:09,515 - Shuake.py[line:374] - INFO: 运行
2020-10-21 21:28:10,088 - Shuake.py[line:199] - ERROR: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 178, in shuake
    cardsInfoList, reportInfo, success = self.get_cards_info(knowledge, num)
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 124, in get_cards_info
    clazzid = knowledge['clazzId']
KeyError: 'clazzId'
2020-10-21 21:28:10,089 - Shuake.py[line:200] - INFO: 18845142702	刷课意外
2020-10-21 21:28:22,019 - Shuake.py[line:374] - INFO: 运行
2020-10-21 21:28:27,148 - Shuake.py[line:342] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 326, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-21 21:28:27,149 - Shuake.py[line:343] - INFO: 18845142702	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 21:28:27,281 - Shuake.py[line:342] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 326, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-21 21:28:27,281 - Shuake.py[line:343] - INFO: 18845142702	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 21:28:28,023 - Shuake.py[line:342] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 326, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-21 21:28:28,023 - Shuake.py[line:343] - INFO: 18845142702	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 21:41:34,261 - Shuake.py[line:380] - INFO: 运行
2020-10-21 21:41:34,734 - Shuake.py[line:123] - ERROR: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 119, in init_knowledegList
    self.knowlegeList[course["id"]].sort(key=knowledeg_sort)
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 106, in knowledeg_sort
    return knowlege["knowlegeId"]+jDict[knowlege["parentnodeid"]][index]*1000000000
KeyError: 7
2020-10-21 21:41:34,735 - Shuake.py[line:124] - INFO: 18845142702	获取课程列表失败
2020-10-21 21:42:14,389 - Shuake.py[line:380] - INFO: 运行
2020-10-21 21:42:18,535 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 332, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-21 21:42:18,536 - Shuake.py[line:349] - INFO: 18845142702	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 21:42:18,642 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 332, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-21 21:42:18,643 - Shuake.py[line:349] - INFO: 18845142702	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 21:42:19,347 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 332, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-21 21:42:19,347 - Shuake.py[line:349] - INFO: 18845142702	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 21:42:20,060 - Shuake.py[line:203] - ERROR: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 199, in shuake
    self.watch_video(cardInfo,reportInfo, knowledge,  scoreInfo)
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 208, in watch_video
    if cardInfo['isPassed']:
KeyError: 'isPassed'
2020-10-21 21:42:20,060 - Shuake.py[line:204] - INFO: 18845142702	刷课意外
2020-10-21 21:43:20,558 - Shuake.py[line:380] - INFO: 运行
2020-10-21 21:43:25,976 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 332, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-21 21:43:25,978 - Shuake.py[line:349] - INFO: 18845142702	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 21:43:26,127 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 332, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-21 21:43:26,128 - Shuake.py[line:349] - INFO: 18845142702	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 21:43:27,372 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 332, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-21 21:43:27,373 - Shuake.py[line:349] - INFO: 18845142702	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 21:51:10,030 - Shuake.py[line:380] - INFO: 运行
2020-10-21 21:51:15,127 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 332, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-21 21:51:15,128 - Shuake.py[line:349] - INFO: 18845142702	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 21:51:15,243 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 332, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-21 21:51:15,244 - Shuake.py[line:349] - INFO: 18845142702	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 21:51:15,943 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 332, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-21 21:51:15,943 - Shuake.py[line:349] - INFO: 18845142702	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 21:53:43,426 - Shuake.py[line:380] - INFO: 运行
2020-10-21 21:53:47,973 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 332, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-21 21:53:47,974 - Shuake.py[line:349] - INFO: 18845142702	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 21:53:48,088 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 332, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-21 21:53:48,089 - Shuake.py[line:349] - INFO: 18845142702	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 21:53:48,820 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 332, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-21 21:53:48,820 - Shuake.py[line:349] - INFO: 18845142702	获取chapter_info 失败  可能是资源下线，不是程序错误
