2020-10-15 21:45:09,471 - Shuake.py[line:103] - INFO: 运行
2020-10-15 21:45:09,771 - Shuake.py[line:53] - ERROR: 
Traceback (most recent call last):
  File "C:/Users/wangwen/Desktop/chaoxing_auto_sign-latest/com/main/Shuake.py", line 50, in login
    self.puid = re.search(r"puid\":(.*?),", resp).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2020-10-15 21:45:09,773 - Shuake.py[line:54] - INFO: 15037671931登陆失败
2020-10-15 21:45:09,773 - Shuake.py[line:123] - INFO: 贾新磊	： 密码错误
2020-10-15 21:47:02,541 - Shuake.py[line:103] - INFO: 运行
2020-10-15 22:00:07,550 - Shuake.py[line:104] - INFO: 运行
