2020-10-21 10:02:35,602 - Shuake.py[line:409] - INFO: 运行
2020-10-21 10:02:49,892 - Shuake.py[line:409] - INFO: 运行
2020-10-21 17:10:56,519 - Shuake.py[line:412] - INFO: 运行
2020-10-21 17:13:20,037 - Shuake.py[line:154] - ERROR: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 142, in init_PageList
    self.pageList[int(page['courseId'])].append(_page)
KeyError: 215091538
2020-10-21 17:13:20,039 - Shuake.py[line:155] - INFO: 18845142702	获取视频列表失败
2020-10-21 17:13:42,584 - Shuake.py[line:412] - INFO: 运行
2020-10-21 17:13:43,453 - Shuake.py[line:154] - ERROR: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 144, in init_PageList
    self.pageList[int(page['courseId'])].append(_page)
KeyError: 215091538
2020-10-21 17:13:43,456 - Shuake.py[line:155] - INFO: 18845142702	获取视频列表失败
2020-10-21 17:14:08,610 - Shuake.py[line:413] - INFO: 运行
2020-10-21 17:14:09,424 - Shuake.py[line:155] - ERROR: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 144, in init_PageList
    self.pageList[int(page['courseId'])].append(_page)
KeyError: 215091538
2020-10-21 17:14:09,426 - Shuake.py[line:156] - INFO: 18845142702	获取视频列表失败
2020-10-21 17:17:01,016 - Shuake.py[line:421] - INFO: 运行
2020-10-21 17:18:51,867 - Shuake.py[line:421] - INFO: 运行
2020-10-21 17:26:48,521 - Shuake.py[line:421] - INFO: 运行
2020-10-21 17:27:53,696 - Shuake.py[line:421] - INFO: 运行
2020-10-21 17:36:41,961 - Shuake.py[line:427] - INFO: 运行
2020-10-21 17:43:43,749 - Shuake.py[line:426] - INFO: 运行
2020-10-21 17:43:44,328 - Shuake.py[line:166] - ERROR: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 128, in init_PageList
    if self.jnodeList[jnodeid]['coursename'] == "四史学习":
TypeError: list indices must be integers or slices, not dict
2020-10-21 17:43:44,329 - Shuake.py[line:167] - INFO: 18845142702	获取视频列表失败
2020-10-21 17:43:49,806 - Shuake.py[line:426] - INFO: 运行
2020-10-21 17:49:44,778 - Shuake.py[line:431] - INFO: 运行
2020-10-21 17:49:45,450 - Shuake.py[line:98] - ERROR: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 95, in init_jnodeList
    self.jnodeList[courseId].sort(key=jnode_sort)
TypeError: jnode_sort() missing 1 required positional argument: 'jnode2'
2020-10-21 17:49:45,452 - Shuake.py[line:99] - INFO: 18845142702	获取课程列表失败
2020-10-21 17:49:45,453 - Shuake.py[line:171] - ERROR: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 133, in init_PageList
    if self.jnodeList[jnodeid]['coursename'] == "四史学习":
TypeError: list indices must be integers or slices, not str
2020-10-21 17:49:45,454 - Shuake.py[line:172] - INFO: 18845142702	获取视频列表失败
2020-10-21 17:51:38,228 - Shuake.py[line:431] - INFO: 运行
2020-10-21 17:52:58,864 - Shuake.py[line:431] - INFO: 运行
2020-10-21 18:57:11,825 - Shuake.py[line:431] - INFO: 运行
2020-10-21 19:06:34,269 - Shuake.py[line:431] - INFO: 运行
2020-10-21 19:06:34,570 - Shuake.py[line:58] - ERROR: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 55, in login
    self.puid = re.search(r"puid\":(.*?),", resp).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2020-10-21 19:06:34,572 - Shuake.py[line:59] - INFO: 18845142702登陆失败
2020-10-21 19:06:34,572 - Shuake.py[line:418] - INFO: 王文安	： 密码错误
2020-10-21 19:06:45,446 - Shuake.py[line:431] - INFO: 运行
2020-10-21 21:24:00,905 - Shuake.py[line:374] - INFO: 运行
2020-10-21 21:27:38,760 - Shuake.py[line:374] - INFO: 运行
2020-10-21 21:27:39,350 - Shuake.py[line:199] - ERROR: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 178, in shuake
    cardsInfoList, reportInfo, success = self.get_cards_info(knowledge, num)
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 124, in get_cards_info
    clazzid = knowledge['clazzId']
KeyError: 'clazzId'
2020-10-21 21:27:39,351 - Shuake.py[line:200] - INFO: 18845142702	刷课意外
2020-10-21 21:28:09,515 - Shuake.py[line:374] - INFO: 运行
2020-10-21 21:28:10,088 - Shuake.py[line:199] - ERROR: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 178, in shuake
    cardsInfoList, reportInfo, success = self.get_cards_info(knowledge, num)
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 124, in get_cards_info
    clazzid = knowledge['clazzId']
KeyError: 'clazzId'
2020-10-21 21:28:10,089 - Shuake.py[line:200] - INFO: 18845142702	刷课意外
2020-10-21 21:28:22,019 - Shuake.py[line:374] - INFO: 运行
2020-10-21 21:28:27,148 - Shuake.py[line:342] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 326, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-21 21:28:27,149 - Shuake.py[line:343] - INFO: 18845142702	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 21:28:27,281 - Shuake.py[line:342] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 326, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-21 21:28:27,281 - Shuake.py[line:343] - INFO: 18845142702	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 21:28:28,023 - Shuake.py[line:342] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 326, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-21 21:28:28,023 - Shuake.py[line:343] - INFO: 18845142702	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 21:41:34,261 - Shuake.py[line:380] - INFO: 运行
2020-10-21 21:41:34,734 - Shuake.py[line:123] - ERROR: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 119, in init_knowledegList
    self.knowlegeList[course["id"]].sort(key=knowledeg_sort)
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 106, in knowledeg_sort
    return knowlege["knowlegeId"]+jDict[knowlege["parentnodeid"]][index]*1000000000
KeyError: 7
2020-10-21 21:41:34,735 - Shuake.py[line:124] - INFO: 18845142702	获取课程列表失败
2020-10-21 21:42:14,389 - Shuake.py[line:380] - INFO: 运行
2020-10-21 21:42:18,535 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 332, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-21 21:42:18,536 - Shuake.py[line:349] - INFO: 18845142702	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 21:42:18,642 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 332, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-21 21:42:18,643 - Shuake.py[line:349] - INFO: 18845142702	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 21:42:19,347 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 332, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-21 21:42:19,347 - Shuake.py[line:349] - INFO: 18845142702	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 21:42:20,060 - Shuake.py[line:203] - ERROR: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 199, in shuake
    self.watch_video(cardInfo,reportInfo, knowledge,  scoreInfo)
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 208, in watch_video
    if cardInfo['isPassed']:
KeyError: 'isPassed'
2020-10-21 21:42:20,060 - Shuake.py[line:204] - INFO: 18845142702	刷课意外
2020-10-21 21:43:20,558 - Shuake.py[line:380] - INFO: 运行
2020-10-21 21:43:25,976 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 332, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-21 21:43:25,978 - Shuake.py[line:349] - INFO: 18845142702	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 21:43:26,127 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 332, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-21 21:43:26,128 - Shuake.py[line:349] - INFO: 18845142702	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 21:43:27,372 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 332, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-21 21:43:27,373 - Shuake.py[line:349] - INFO: 18845142702	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 21:51:10,030 - Shuake.py[line:380] - INFO: 运行
2020-10-21 21:51:15,127 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 332, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-21 21:51:15,128 - Shuake.py[line:349] - INFO: 18845142702	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 21:51:15,243 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 332, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-21 21:51:15,244 - Shuake.py[line:349] - INFO: 18845142702	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 21:51:15,943 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 332, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-21 21:51:15,943 - Shuake.py[line:349] - INFO: 18845142702	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 21:53:43,426 - Shuake.py[line:380] - INFO: 运行
2020-10-21 21:53:47,973 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 332, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-21 21:53:47,974 - Shuake.py[line:349] - INFO: 18845142702	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 21:53:48,088 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 332, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-21 21:53:48,089 - Shuake.py[line:349] - INFO: 18845142702	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 21:53:48,820 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 332, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-21 21:53:48,820 - Shuake.py[line:349] - INFO: 18845142702	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:12:59,981 - Shuake.py[line:380] - INFO: 运行
2020-10-21 22:13:00,840 - Shuake.py[line:123] - ERROR: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 117, in init_knowledegList
    "parentnodeNmae":jDict[knowlege["parentnodeid"]]["name"],
KeyError: 349156546
2020-10-21 22:13:00,841 - Shuake.py[line:124] - INFO: 18925468581	获取课程列表失败
2020-10-21 22:13:04,689 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:04,690 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:05,029 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:05,029 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:05,283 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:05,284 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:05,537 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:05,538 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:05,753 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:05,754 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:05,975 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:05,976 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:06,191 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:06,192 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:06,348 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:06,349 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:06,741 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:06,742 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:06,966 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:06,967 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:07,213 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:07,213 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:07,379 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:07,380 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:07,608 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:07,609 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:07,765 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:07,766 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:07,920 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:07,921 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:08,060 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:08,061 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:08,209 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:08,209 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:08,358 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:08,359 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:08,586 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:08,587 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:08,813 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:08,813 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:08,965 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:08,965 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:09,202 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:09,203 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:09,367 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:09,367 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:09,637 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:09,638 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:10,524 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:10,525 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:10,650 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:10,651 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:10,805 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:10,805 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:11,010 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:11,011 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:11,167 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:11,168 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:11,384 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:11,385 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:11,540 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:11,540 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:11,761 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:11,762 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:11,938 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:11,939 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:12,144 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:12,144 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:12,291 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:12,291 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:12,490 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:12,491 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:12,712 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:12,713 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:12,949 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:12,950 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:13,108 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:13,109 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:13,540 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:13,541 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:13,754 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:13,755 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:13,903 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:13,904 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:14,115 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:14,116 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:14,413 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:14,413 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:14,576 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:14,577 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:14,787 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:14,788 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:15,077 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:15,078 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:15,265 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:15,266 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:15,521 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:15,522 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:15,673 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:15,673 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:15,889 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:15,890 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:16,095 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:16,095 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:16,308 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:16,308 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:16,457 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:16,457 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:16,604 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:16,604 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:16,822 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:16,823 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:16,967 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:16,968 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:17,122 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:17,122 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:17,280 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:17,280 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:17,431 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:17,432 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:17,582 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:17,583 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:17,777 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:17,777 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:17,977 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:17,978 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:18,135 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:18,135 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:18,345 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:18,346 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:18,576 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:18,576 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:18,911 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:18,911 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:19,060 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:19,060 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:19,275 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:19,275 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:19,438 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:19,438 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:13:19,707 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:13:19,707 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:14:50,324 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:14:50,325 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:14:50,489 - Shuake.py[line:348] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 330, in get_chapters_info
    soup = BeautifulSoup(response.text, "lxml")
  File "D:\Program Files\develop\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2020-10-21 22:14:50,490 - Shuake.py[line:349] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-21 22:18:41,389 - Shuake.py[line:380] - INFO: 运行
2020-10-21 22:18:42,361 - Shuake.py[line:123] - ERROR: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 117, in init_knowledegList
    "parentnodeNmae":jDict[knowlege["parentnodeid"]]["name"],
KeyError: 349156546
2020-10-21 22:18:42,363 - Shuake.py[line:124] - INFO: 18925468581	获取课程列表失败
2020-10-21 22:18:42,544 - Shuake.py[line:145] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 140, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:18:42,546 - Shuake.py[line:146] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:18:42,624 - Shuake.py[line:145] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 140, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:18:42,625 - Shuake.py[line:146] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:18:42,701 - Shuake.py[line:145] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 140, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:18:42,702 - Shuake.py[line:146] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:18:42,781 - Shuake.py[line:145] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 140, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:18:42,782 - Shuake.py[line:146] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:18:43,004 - Shuake.py[line:145] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 140, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:18:43,006 - Shuake.py[line:146] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:18:43,084 - Shuake.py[line:145] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 140, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:18:43,085 - Shuake.py[line:146] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:18:43,165 - Shuake.py[line:145] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 140, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:18:43,166 - Shuake.py[line:146] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:18:43,375 - Shuake.py[line:145] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 140, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:18:43,376 - Shuake.py[line:146] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:18:43,455 - Shuake.py[line:145] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 140, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:18:43,455 - Shuake.py[line:146] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:18:43,529 - Shuake.py[line:145] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 140, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:18:43,530 - Shuake.py[line:146] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:18:43,604 - Shuake.py[line:145] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 140, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:18:43,605 - Shuake.py[line:146] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:18:43,682 - Shuake.py[line:145] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 140, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:18:43,683 - Shuake.py[line:146] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:18:43,875 - Shuake.py[line:145] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 140, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:18:43,876 - Shuake.py[line:146] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:18:43,961 - Shuake.py[line:145] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 140, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:18:43,962 - Shuake.py[line:146] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:18:44,043 - Shuake.py[line:145] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 140, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:18:44,044 - Shuake.py[line:146] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:18:44,123 - Shuake.py[line:145] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 140, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:18:44,123 - Shuake.py[line:146] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:18:44,199 - Shuake.py[line:145] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 140, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:18:44,200 - Shuake.py[line:146] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:21:42,625 - Shuake.py[line:382] - INFO: 运行
2020-10-21 22:21:43,502 - Shuake.py[line:125] - ERROR: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 119, in init_knowledegList
    "parentnodeNmae":jDict[knowlege["parentnodeid"]]["name"],
KeyError: 349156546
2020-10-21 22:21:43,503 - Shuake.py[line:126] - INFO: 18925468581	获取课程列表失败
2020-10-21 22:21:43,668 - Shuake.py[line:147] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 142, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:21:43,669 - Shuake.py[line:148] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:21:43,748 - Shuake.py[line:147] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 142, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:21:43,749 - Shuake.py[line:148] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:21:43,830 - Shuake.py[line:147] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 142, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:21:43,831 - Shuake.py[line:148] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:21:43,915 - Shuake.py[line:147] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 142, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:21:43,916 - Shuake.py[line:148] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:21:44,088 - Shuake.py[line:147] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 142, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:21:44,090 - Shuake.py[line:148] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:21:44,177 - Shuake.py[line:147] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 142, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:21:44,178 - Shuake.py[line:148] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:21:44,273 - Shuake.py[line:147] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 142, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:21:44,274 - Shuake.py[line:148] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:21:44,456 - Shuake.py[line:147] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 142, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:21:44,456 - Shuake.py[line:148] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:21:44,537 - Shuake.py[line:147] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 142, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:21:44,538 - Shuake.py[line:148] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:21:44,618 - Shuake.py[line:147] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 142, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:21:44,619 - Shuake.py[line:148] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:21:44,703 - Shuake.py[line:147] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 142, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:21:44,704 - Shuake.py[line:148] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:21:44,788 - Shuake.py[line:147] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 142, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:21:44,789 - Shuake.py[line:148] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:21:44,964 - Shuake.py[line:147] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 142, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:21:44,964 - Shuake.py[line:148] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:21:45,044 - Shuake.py[line:147] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 142, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:21:45,045 - Shuake.py[line:148] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:21:45,134 - Shuake.py[line:147] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 142, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:21:45,135 - Shuake.py[line:148] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:21:45,223 - Shuake.py[line:147] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 142, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:21:45,224 - Shuake.py[line:148] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:21:45,316 - Shuake.py[line:147] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 142, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:21:45,317 - Shuake.py[line:148] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:25:00,748 - Shuake.py[line:382] - INFO: 运行
2020-10-21 22:25:01,319 - Shuake.py[line:125] - ERROR: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 119, in init_knowledegList
    "parentnodeNmae":knowlege["parentnodeid"] if knowlege["parentnodeid"] not in jDict[knowlege["parentnodeid"]]["name"] else jDict[knowlege["parentnodeid"]]["name"],
TypeError: 'in <string>' requires string as left operand, not int
2020-10-21 22:25:01,319 - Shuake.py[line:126] - INFO: 18925468581	获取课程列表失败
2020-10-21 22:25:29,820 - Shuake.py[line:382] - INFO: 运行
2020-10-21 22:25:31,122 - Shuake.py[line:147] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 142, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:25:31,125 - Shuake.py[line:148] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:25:31,577 - Shuake.py[line:147] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 142, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:25:31,577 - Shuake.py[line:148] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:25:31,654 - Shuake.py[line:147] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 142, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:25:31,654 - Shuake.py[line:148] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:25:31,735 - Shuake.py[line:147] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 142, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:25:31,736 - Shuake.py[line:148] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:25:31,932 - Shuake.py[line:147] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 142, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:25:31,932 - Shuake.py[line:148] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:25:32,012 - Shuake.py[line:147] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 142, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:25:32,012 - Shuake.py[line:148] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:25:32,094 - Shuake.py[line:147] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 142, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:25:32,095 - Shuake.py[line:148] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:25:32,262 - Shuake.py[line:147] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 142, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:25:32,262 - Shuake.py[line:148] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:25:32,341 - Shuake.py[line:147] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 142, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:25:32,341 - Shuake.py[line:148] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:25:32,417 - Shuake.py[line:147] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 142, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:25:32,417 - Shuake.py[line:148] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:25:32,490 - Shuake.py[line:147] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 142, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:25:32,490 - Shuake.py[line:148] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:25:32,565 - Shuake.py[line:147] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 142, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:25:32,565 - Shuake.py[line:148] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:25:32,714 - Shuake.py[line:147] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 142, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:25:32,714 - Shuake.py[line:148] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:25:32,800 - Shuake.py[line:147] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 142, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:25:32,800 - Shuake.py[line:148] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:25:32,886 - Shuake.py[line:147] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 142, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:25:32,887 - Shuake.py[line:148] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:25:32,970 - Shuake.py[line:147] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 142, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:25:32,971 - Shuake.py[line:148] - INFO: 18925468581	获取视cards息失败
2020-10-21 22:25:33,060 - Shuake.py[line:147] - INFO: 
Traceback (most recent call last):
  File "D:/Program Files/PythonWorkSpace/chaoxingxing/com/main/Shuake.py", line 142, in get_cards_info
    cardsInfo = json.loads(cardsInfo)
  File "D:\Program Files\develop\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\develop\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\develop\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-21 22:25:33,061 - Shuake.py[line:148] - INFO: 18925468581	获取视cards息失败
